### ISSUE TITLE
There is no text-left in bootstrap 5 any more

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-zeitungen-static#10]
It's text-start and text-end now

Also I think it is good practice to have headings always start with h1 then h2 and so on... . The size/look of the h should be adjusted otherwise. Good old separation of look and semantics.

https://github.com/arthur-schnitzler/schnitzler-zeitungen-static/blob/65b3e375db9e4d58a998d8e571936545ff829b8b/templates/static/index.j2#L13

**Comment by martinantonmueller** [comment]
I feel reprimanded. Rightly so. Will take care.
