### ISSUE TITLE
quotation + implement concordance 

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-zeitungen-static#2]
analogue to 
https://github.com/arthur-schnitzler/schnitzler-mikrofilme-static/issues/6

this concordance should be implemented and displayed on top of the page in order to have a proper quotation:

https://docs.google.com/spreadsheets/d/1FyPgOydzc95Pk-2e9qj3xNevg9ZbcwaMZEglepdrVBk/edit?usp=sharing

e.g.
II. Theaterstücke, 26, 3 Komödie der Worte: Große Szene

**Comment by martinantonmueller** [comment]
I've added a column "PMB" with pmb-numbers where available

**Comment by csae8092** [comment]
@martinantonmueller  könntest du hier https://github.com/arthur-schnitzler/schnitzler-zeitungen-static/blob/main/project.json#L6

bitte hinschreiben beim zitiervorschlag nach: `in: ` stehen soll. ich hab da ein wenig blödsin hineinkopiert

**Comment by martinantonmueller** [comment]
Done
