### ISSUE TITLE
make page as good looking as the old one

### ISSUE THREAD

**Issue by csae8092** [arthur-schnitzler/schnitzler-zeitungen-static#6]
ToDo for @martinantonmueller: The footer

You should be able to develop locally without much troubles by
* cloning the repo
* installing python packages `pip install -r requirements.txt`
* running `python build_static.py` which only builds html files from the `templates/static` folder
* to build the whole application you can run `./build.sh` but this takes some minutes (~5) and throws an error while trying to build the typesense index

the main css file is located here: https://github.com/arthur-schnitzler/schnitzler-zeitungen-static/blob/main/html/css/style.css
the file for the footer is located here: https://github.com/arthur-schnitzler/schnitzler-zeitungen-static/blob/main/templates/partials/footer.j2

have fun!

**Comment by martinantonmueller** [comment]
I‘m on holidays until the end of the week. Will do everything afterwards
